title: AM Fermino
email: info@amfermino.com
description: >- # this means to ignore newlines until "baseurl:"
  Soluções Ambientais
url: "http://amfermino.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-email-protect
  - jekyll-seo-tag
  - jekyll-analytics

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bower_components

# assets
sass:
  sass_dir: assets/_sass
  style: compressed

logo: /assets/img/logo.svg
image: /assets/img/logotipo.svg
color: "#49733d"

collections_dir: collections
collections:
  sobre:
  servicos:
  portfolio:

pagination:
  enabled: true
  per_page: 15
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2