title: Lente Mágica
email: info@lentemagica.com
description: >- # this means to ignore newlines until "baseurl:"
  Capturando Momentos Mágicos
url: "https://lentemagica.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-email-protect
  - jekyll-seo-tag
  - jekyll-analytics

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bower_components

# assets
sass:
  sass_dir: assets/_sass
  style: compressed

logo: /assets/img/whitelogo.svg
image: /assets/img/goldlogo.svg
logotype: /assets/img/blacklogo.svg
color: "#444"

collections_dir: collections
collections:
  sobre:
  servicos:
  galeria:
  slider:

pagination:
  enabled: true
  per_page: 15
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2